### ISSUE TITLE
No syntax highlighting?

### ISSUE THREAD

**Issue by lomori** [ryanburns23/show-json#1]
Hi,
Nice component. I'm trying ti but don't see the syntax highlighting. Any idea of what could be wrong?
Regards,
Luiz

**Comment by ryanburns23** [comment]
@lomori  Not unless you can give me some more info, the [demo's ](https://www.webcomponents.org/element/ryanburns23/show-json/demo/demo/index.html)seem to be working fine.

Syntax highlighting is handled by the [prism-element](https://www.webcomponents.org/element/PolymerElements/prism-element)

**Comment by lomori** [comment]
It seems to be some interference from Polymer Starter Kit. Yes, per se the demo works but it doesn't when I put inside one of the PSK cards.

**Comment by ryanburns23** [comment]
@lomori  It looks like there was a missing style include tag 

I'll tag a new release now, if you use that you should be fine. 
Thanks for the info.

**Comment by lomori** [comment]
Yes, it works now. Thanks!
